import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Rightaside from "@/components/Rightaside";
import Leftaside from "@/components/Leftaside";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main>
          <div className="row m-2 mt-3">
            <Leftaside/>
            <div className="col-6 r_tbdr" >
            {children}
            </div>
            <Rightaside/>
          </div>
        </main>
        <Footer/>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
      </body>
    </html>
  )
}